import * as XLSX from 'xlsx';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
// import type { TimesheetRow, RaceDistance, SwimStyle, PaceType } from './paceCalculator';
import type { TimesheetRow, RaceDistance, PaceType } from './paceCalculator';
import { formatTime } from './paceCalculator';

/**
 * Export timesheet data to CSV format
 */
export function exportToCSV(
  timesheet: TimesheetRow[],
  raceDistance: RaceDistance,
  // swimStyle: SwimStyle,
  paceType: PaceType
): void {
  if (timesheet.length === 0) return;

  const splitColumns = Object.keys(timesheet[0].splits);

  // Build CSV content
  // let csv = `Swimming Timesheet - ${raceDistance}m ${swimStyle} (${paceType})\n\n`;
  let csv = `Training Timesheet - ${raceDistance}m (${paceType})\n\n`;
  csv += `Target (${raceDistance}m),${splitColumns.join(',')}\n`;

  timesheet.forEach((row) => {
    const values = [
      `${row.target[0]}% :: ${formatTime(row.target[1])}`,
      ...splitColumns.map((col) => formatTime(row.splits[col])),
    ];
    csv += values.join(',') + '\n';
  });

  // Download CSV
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  // link.setAttribute('download', `training-timesheet-${raceDistance}m-${swimStyle}.csv`);
  link.setAttribute('download', `training-timesheet-${raceDistance}m.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

/**
 * Export timesheet data to Excel format
 */
export function exportToExcel(
  timesheet: TimesheetRow[],
  raceDistance: RaceDistance,
  // swimStyle: SwimStyle,
  paceType: PaceType
): void {
  if (timesheet.length === 0) return;

  const splitColumns = Object.keys(timesheet[0].splits);

  // Prepare data for Excel
  const headers = [`Target (${raceDistance}m)`, ...splitColumns];

  const data = timesheet.map((row) => [
    `${row.target[0]}% :: ${formatTime(row.target[1])}`,
    ...splitColumns.map((col) => formatTime(row.splits[col])),
  ]);

  const worksheetData = [
    // [`Training Timesheet - ${raceDistance}m ${swimStyle}`],
    [`Training Timesheet - ${raceDistance}m`],
    [`Pace Strategy: ${paceType}`],
    [],
    headers,
    ...data,
  ];

  // Create workbook and worksheet
  const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Timesheet');

  // Style header row
  worksheet['!cols'] = headers.map(() => ({ wch: 15 }));

  // Download Excel file
  // XLSX.writeFile(workbook, `training-timesheet-${raceDistance}m-${swimStyle}.xlsx`);
  XLSX.writeFile(workbook, `training-timesheet-${raceDistance}m.xlsx`);
}

/**
 * Export timesheet data to PDF format
 */
export function exportToPDF(
  timesheet: TimesheetRow[],
  raceDistance: RaceDistance,
  // swimStyle: SwimStyle,
  paceType: PaceType
): void {
  if (timesheet.length === 0) return;

  const splitColumns = Object.keys(timesheet[0].splits);

  const doc = new jsPDF({
    orientation: splitColumns.length > 6 ? 'landscape' : 'portrait',
  });

  // Title
  doc.setFontSize(18);
  doc.text(`Training Pace Calculator`, 14, 20);

  doc.setFontSize(12);
  // doc.text(`Race: ${raceDistance}m ${swimStyle}`, 14, 30);
  doc.text(`Race: ${raceDistance}m`, 14, 30);
  doc.text(`Pace Strategy: ${paceType}`, 14, 37);

  // Prepare table data
  const headers = [[`Target (${raceDistance}m)`, ...splitColumns]];

  const data = timesheet.map((row) => [
    `${row.target[0]}% :: ${formatTime(row.target[1])}`,
    ...splitColumns.map((col) => formatTime(row.splits[col])),
  ]);

  // Generate table
  autoTable(doc, {
    head: headers,
    body: data,
    startY: 45,
    theme: 'grid',
    headStyles: {
      fillColor: [102, 126, 234],
      fontSize: 10,
      fontStyle: 'bold',
    },
    bodyStyles: {
      fontSize: 9,
    },
    alternateRowStyles: {
      fillColor: [248, 249, 250],
    },
    columnStyles: {
      0: { fontStyle: 'bold', fillColor: [248, 249, 250] },
    },
  });

  // Add footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(
      `Generated by Ritmo.AI - Page ${i} of ${pageCount}`,
      14,
      doc.internal.pageSize.height - 10
    );
  }

  // Download PDF
  // doc.save(`training-timesheet-${raceDistance}m-${swimStyle}.pdf`);
  doc.save(`training-timesheet-${raceDistance}m.pdf`);
}
